### ISSUE TITLE
add a copy mode which replicate Edge's copy URL behaviour (copy as html anchor with page title text) 

### ISSUE THREAD

**Issue by cattledogit** [igorlogius/get-tabs-infos#1]
How can copytabinfo be used to replicate the copy/paste functionality now in MS Edge that's described in the Reddit thread "Any way to use the copy&paste URL/title feature of Edge in FF? (pasting the title of the site)"? In that thread at https://www.reddit.com/r/firefox/comments/nh9dyw/comment/gyvdle7/?utm_source=share&utm_medium=web2x&context=3 igorlogius wrote: "I didn't yet add a shortcut, but if you need one, i can add it. Just reply here or add an issue on the github site."

The MS Edge feature, new in 2020, is described at https://support.microsoft.com/en-us/microsoft-edge/improved-copy-and-paste-of-urls-in-microsoft-edge-d3bd3956-603a-0033-1fbc-9588a30645b4.

Thanks for copytabinfo!

**Comment by igorlogius** [comment]
@cattledogit 
Some reviewer on AMO thinks the copy-taburl-html and copy-taburl are too similar and that is why copy-taburl-html has  currently been disabled. 

I am currently trying to explain  that both addons are distinctly different from each other, but since his/her response rate is ... rather slow, i thought i leave a comment here just in case.

**Comment by igorlogius** [comment]
It might be possible to  construct a partial html element list  

<ul>
<li><a href="..">Page Title 1</a></li>
<li><a href="..">Page Title 2</a></li>
<li><a href="..">Page Title 3</a></li>
</ul>

and copy that into the clipboard buffer ... 
Not sure if that would actually behave / work as a user would expect ... but it might 

Have to do some testing with this.

**Comment by igorlogius** [comment]
I'll have to take another look at this soonish ...

**Comment by cattledogit** [comment]
Thank you. "Copy tab URL as HTML" works just fine in the meantime.

    On Sunday, February 6, 2022, 02:32:35 PM EST, igorlogius ***@***.***> wrote:  
 
 


I'll have to take another look at this soonish ...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by igorlogius** [comment]
support generic html is a bit to much for this addon, i might add the option to copy multiple or all  urls as html to the copy-taburls-html 
addon, maybe via an addional toolbar button. Closing this for now.
